use 96r;
create table employe (em_id int primary key,em_name varchar(60),department varchar(70),salary int,city char(60),experience int);
insert into employe values(101,"irfan","IT",70000,"chennai",8);
insert into employe values(102,"deeepu","HR",90000,"USA",9);
insert into employe values(103,"sri","finance",80000,"HYD",7);
insert into employe values(104,"rajeswari","Manager",60000,"bangloore",6);
insert into employe values(105,"bhanu","HR",560000,"america",4);
insert into employe values(106,"shirisha","IT",40000,"chicago",5);
insert into employe values(107,"rohitha","HR",30000,"pune",2);
insert into employe values(108,"navya","IT",550000,"mumbai",3);
select * from employe;
update employe set department="IT" where em_id=102;
select * from employe;
select * from employe where salary>=80000
select * from employe where department="IT";
select * from employe where experience>=3;
select * from employe where experience<=3;
select * from employe where department="HR" and city="pune";
select * from employe where salary between 30000 and 70000;
select distinct department from employe;
select * from employe order by experience;
select em_id,em_name from employe  order by salary;
select * from employe order by em_name ASC;
select * from employe limit 3;
select * from employe order by salary desc limit 5;
select count(*) as total_employees from employe;
select count(em_name)as total_employees  from employe where department="IT";
select sum(salary) from employe;
select sum(salary) from employe where department="HR";
select avg(experience) from employe;
select min(salary) from employe;
select max(salary) from employe;
select  department, COUNT(*)as total_employees from employe group by department;
select department,sum(salary) as sum_salary from employe group by department;
select department ,avg(salary) as avg_salary from employe group by department;
select department,max(salary) as mximum_salary from employe group by department;
select department,count(*)  as total_employees from employe group by department having count(*)>2;
select department, sum(salary) as sum_salry from employe group by department having sum(salary)>=550000;
select * from employe limit 5 offset 2;
select * from employe order by salary desc limit 1 offset 3;
