use 96r;
create table studentdetails(stu_id int primary key,stu_name char(70),stu_age int,stu_course char(70),stu_city char(70),stu_email varchar(70),stu_phone bigint,stu_adharno varchar(70));
insert into studentdetails values(1,"deepika",21,"DATASCIENCE","Guntur","deepika@gmail.com",1234567890,876549089);
insert into studentdetails values(2,"Navya",21,"CSE","Guntur","Navya@gmail.com",2327865439,098765433);
insert into studentdetails values(3,"Bhanusri",21,"IT","Guntur","bhanu@gmail.com",78906543902,987654390);
insert into studentdetails values(4,"veena",22,"ECE","Tenali","veena@gmail.com",0033778866,234509176);
insert into studentdetails values(5,"priya",23,"EEE","CHINTUGUNTTA","priya@gmail.com",6754098417,905064064);
select * from studentdetails;
create view studen_detail as select * from studentdetails;
select  * from studen_detail;
create view studen_details as select  stu_id,stu_name,stu_course,stu_phone from studentdetails where stu_age=21;
select * from studen_details;
create view guntur_student as select stu_id,stu_name,stu_course,stu_city from studentdetails where stu_city="Guntur";
select * from guntur_student;
create view contact_details as select stu_name,stu_email,stu_phone from studentdetails ;
select * from contact_details;
create view young_students as select stu_name,stu_course,stu_city from studentdetails where stu_age>21;
select * from young_students;
create view phone_details as select stu_id,stu_name,stu_phone from studentdetails;
update  phone_details set stu_phone=1234560097 where stu_id=3;
select * from phone_details;
select* from studentdetails;
create view city_details as select stu_id,stu_name,stu_city from studentdetails;
update city_details set stu_city="USA" where stu_id=1;
select * from city_details;
select * from studentdetails;
