use 96r;
select * from employees;
select *, row_number() over()from employees;
select * ,row_number() over (order by emp_salary desc) from employees;
select *, row_number() over (order by emp_salary desc) as row_number1 from employees;
select * ,row_number() over(partition by emp_department) as dept_s1 from employees;
select*,row_number() over(partition by emp_name)as emp_e1 from employees;
select *,rank()over() from employees;
select * ,rank() over(order by emp_salary desc) from employees;
select * ,rank() over(partition by emp_department order by emp_salary desc) as rank_emp from employees;
select *,dense_rank() over() from employees;
select *,dense_rank() over(order by emp_salary desc) from employees;
select *,rank() over(order by emp_salary desc)from employees;
select *,dense_rank() over(partition by emp_department order by emp_salary desc)from employees;
select *,lead(emp_name)over()from employees;
select *,lead(emp_salary)over()from employees;
select *,lead(emp_salary)over(partition by emp_department order by emp_salary desc )from employees;
select *, lag(emp_name) over() from employees;
select *,lag(emp_name)over( partition by emp_department order by emp_salary desc)from employees;